### ISSUE TITLE
Streambuilder with EVEN MORE Streams?

### ISSUE THREAD

**Issue by rokk4** [glitchedmob/flutter_multiple_stream_builder#5]
First of all, thanks for this very useful package!

I have an app with a lot of lists, each of them comes from different DB Stream.
There are 3 Main Categories and 6 Sub, so I would need a Streambuilder16 .
I would say that's not a rare usecase if building internal enterprise software.

Would be nice if you would consider adding StreambuilderXX up to 32 I would guess.

**Comment by glitchedmob** [comment]
@rokk4 hahahah I wondered when this would happen!

However, I'm not planning to add any way to support more than 15 streams in a single widget.

I would say at that point you're probably better off nesting multiple `StreamBuilder` widgets to unwrap all these streams. It might even be worth building a custom widget in your application that does this and accepts a single builder argument that is passed all all of the data from the multiple `StreamBuilder` instances.

Here's a stripped down example of what I'm talking about

```dart
// Type definition for our custom builder callback
typedef MyCustomWidgetBuilder = Widget Function(
  BuildContext context,
  MySnapshot snapshot,
);

class MyCustomStreamBuilder extends StatelessWidget {
  final MyCustomWidgetBuilder builder;

  const MyCustomStreamBuilder({Key? key, required this.builder})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return StreamBuilder8(
      streams: StreamTuple8(/* streams */),
      builder: (context1, snapshot1) {
        return StreamBuilder8(
          streams: StreamTuple8(/* other streams */),
          builder: (context, snapshot2) {
            final snapshot; // build MySnapshot from snapshot1 and snapshot2;
            return builder(context, snapshot2);
          },
        );
      },
    );
  }
}
```

This would require you to build additional abstractions, such as the `MySnapshot` not shown here, but the final result would like be something that's a bit more reusable anyways.

Hope this helps!
